allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  'dsh-compaction-optical@https://github.com/cyijun/dsh-compaction-optical/releases/download/v0.1.0/dsh-compaction-optical-0.1.0.tgz': true
  koffi: true
  node-pty: true
  sharp: true
